name: mkdocs build
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.10.6
      - run: pip install mkdocs "mkdocstrings[python]"
      - run: mkdocs gh-deploy --force --clean --verbose
