name: mkdocs build
on:
  push:
    branches:
      - main
    paths:
      - 'src/python_time_manager/engine/**'
      - 'src/python_time_manager/models/**'
      - 'docs/**'
      - 'mkdocs.yml'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.10.6
      - run: pip install mkdocs mkdocs-material "mkdocstrings[python]" mkdocs-git-revision-date-localized-plugin
      - run: mkdocs gh-deploy --force --clean --verbose
